version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_with_restore
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: SmartLinkD
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/backup           # папка с бэкапом на хосте
      - pgdata:/var/lib/postgresql/data # постоянное хранилище данных
      - ./restore_and_start.sh:/docker-entrypoint-initdb.d/restore_and_start.sh:ro
        # или монтировать скрипт так, чтобы он запускался при инициализации базы

    command: ["bash", "-c", "/backup/restore_and_start.sh"]
      
volumes:
  pgdata: