version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_with_restore
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: SmartLinkD
    ports:
      - "5432:5432"
    volumes:
      - ./backup:/backup           # папка с бэкапом на хосте
      - pgdata:/var/lib/postgresql/data # постоянное хранилище данных
      - ./restore_and_start.sh:/docker-entrypoint-initdb.d/restore_and_start.sh:ro
        # скрипт для восстановления базы при инициализации

    command: ["bash", "-c", "/backup/restore_and_start.sh"]

  test:
    build: 
     context: ./Tests          # путь к папке с Dockerfile
    command: bash -c "dotnet test Tests.csproj --collect:\"XPlat Code Coverage\" --results-directory /app/TestResults"
    depends_on:
      - webapi 
    volumes:
      - ./TestResults:/app/TestResults

volumes:
  pgdata: