name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  postgres-restore:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: puser
          POSTGRES_PASSWORD: 111
          POSTGRES_DB: SmartLinkNew
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U puser; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Install psql client
        run: sudo apt-get install -y postgresql-client
        
      - name: List files in backup directory
        run: ls -l ./
        
      - name: List files in backup directory
        run: ls -l ./backup/

      - name: Copy backup file to runner
        run: cp ./backup/SmartLink.backup ./ 

      - name: Restore database from backup
        env:
          PGPASSWORD: 111
        run: |
          pg_restore  -h localhost -U puser -d SmartLinkNew -f SmartLink.backup

      # Установка CONNECTION_STRING для дальнейшего использования
      - name: Set CONNECTION_STRING environment variable
        run: |
          echo "CONNECTION_STRING=Server=localhost;Port=5432;Database=SmartLinkNew;User Id=puser;Password=111;" >> $GITHUB_ENV

      # Далее ваши шаги по сборке и тестам, где можно использовать $CONNECTION_STRING
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        env:
          CONNECTION_STRING: ${{ env.CONNECTION_STRING }}
        run: dotnet build --no-restore

      - name: Run tests with connection string environment variable
        env:
          CONNECTION_STRING: ${{ env.CONNECTION_STRING }}
        run: dotnet test --no-build --verbosity normal --logger:"trx"