name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  postgres-restore:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: puser
          POSTGRES_PASSWORD: 111
          POSTGRES_DB: SmartLinkNew
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U puser; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Install psql client
        run: sudo apt-get install -y postgresql-client
        
      - name: List files in backup directory
        run: ls -l ./
        
      - name: List files in backup directory
        run: ls -l ./backup/

      - name: Copy backup file to runner
        run: cp ./backup/SmartLink.sql ./ 

      - name: Restore database from backup
        env:
          PGPASSWORD: 111
        run: |
          psql -h localhost -U puser -d SmartLinkNew -f SmartLink.sql
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore SmartLinks.sln

      - name: Build        
        run: dotnet build SmartLinks.sln --no-restore

      # Добавляем установку coverlet.collector, если еще не добавлен в проект (можно сделать один раз)
      - name: Add Coverlet Collector package (если не добавлено)
        run: |
          dotnet add Tests/Tests.csproj package coverlet.collector

      # Запуск тестов с сбором покрытия и генерацией отчета в формате opencover или json
      - name: Run tests with coverage collection
        run: |
          dotnet test Tests/Tests.csproj --no-build --verbosity normal \
            --logger:"trx" \
            /p:IsTestProject=true \
            /p:"CollectCoverage=true" \
            /p:"CoverletOutput=coverage/" \
            /p:"CoverletOutputFormat=opencover" \
            --collect:"XPlat Code Coverage"

      - name: Install xmlstarlet for XML parsing
        run: sudo apt-get install -y xmlstarlet

      - name: Extract coverage percentage
        id: coverage
        run: |
          # Путь к файлу отчета (может отличаться)
          COVERAGE_FILE=$(find coverage/ -name "coverage.opencover.xml")
          
          # Извлекаем общее покрытие из XML
          PERCENTAGE=$(xmlstarlet sel -t -v "/*/Summary/@sequenceCoverage" "$COVERAGE_FILE")
          
          echo "Coverage percentage: $PERCENTAGE%"
          
          # Передаем значение в output шага
          echo "::set-output name=percent::$PERCENTAGE"

      - name: Display coverage percentage
        run: echo "Code coverage is ${{ steps.coverage.outputs.percent }}%"