name: .NET

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Установка Docker Compose (если нужно)
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Start Docker Containers
      run: |
        docker-compose up -d
        
    # Ждем, пока сервисы будут готовы (можно использовать sleep или проверку)
      - name: Wait for services to be ready
        run: sleep 30

      # Запуск тестов
      - name: Run Tests
        run: |
          dotnet test ./Tests/Tests.csproj --no-build --verbosity normal
    
    #- name: Setup .NET
     # uses: actions/setup-dotnet@v4
    #  with:
    #    dotnet-version: 8.0.x
        
    #- name: Restore dependencies
    #  run: dotnet restore ./SmartLinks.sln
      
    #- name: Build
    #  run: dotnet build ./SmartLinks.sln
      
    #- name: Test
    #  run: dotnet test ./Tests/Tests.csproj --no-build --verbosity normal
      
    - name: Stop Docker Containers
      if: always()  # чтобы контейнеры останавливались даже при ошибках
      run: |
        docker-compose down